### ISSUE TITLE
base 버전의 tensorflow1 checkpoint 에러

### ISSUE THREAD

**Issue by Scag** [monologg/KoELECTRA#10]
안녕하세요. 구글드라이브 업로드 해주신 체크포인트를 사용하여 tf 1.15 에서 사용을 해보려고 하는데요.

tf.train.init_from_checkpoint(tvars, assign_map)

을 사용하여 가져와보면, 

OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Out of range: Read less bytes than requested

와 같은 에러가 다수 발생합니다.

올려주신 small v2 버전으로는 동일코드에서 잘 돌아가는데요. (small v1 은 미확인)

혹시 체크포인트 자체의 이슈인가 싶어

assign_map 변수에 "초기화 할 var name" 의 whitelist 를 정하여 초기화를 진행해보았는데, 

특정 variable 들을 포함할때 restore 실패가 발생하는데요.

일일히 var name 하나하나 해봐야해서 전부다 찾아보지는 못하였는데, 

확실한건 electra/embedding, layer_0, layer_1, layer_2 까지는 모두 포함하여도 되고, 

layer_3 은 다 되다가 

electra/encoder/layer_3/attention/output/dense/kernel

tensor 를 포함하는순간부터 read 에러가 발생합니다.

base v1, base v2 모두 그러는데 (위 tensor는 base v2의 경우.. v1은 어떤 tensor에서 에러가 나는지는 못보았습니다.)

재다운로드를 몇번해도 동일한걸로 보아 혹시 업로드도중 손상이 되었나 싶기도 한데요.

혹시  tar.gz 등으로 압축하여 드라이브에 재업로드를 부탁드려도 될까요?

감사합니다.

**Comment by monologg** [comment]
@Scag 

해당 부분 확인해보도록 다시 알려드리겠습니다 감사합니다:)

**Comment by monologg** [comment]
@Scag 

해당 부분 체크해서 tar.gz으로 다시 올렸습니다. 이전에 올리는 과정에서 이슈가 있었던 것 같습니다

**Comment by monologg** [comment]
@Scag 

해당 이슈는 닫도록 하겠습니다! 혹시나 이슈가 있으면 다시 오픈해주시면 됩니다:)

**Comment by Scag** [comment]
감사합니다 조금 늦게 확인했는데, 신규로 만들어주신 v3 모델의 압축파일로 잘 되는것 확인하였습니다!
