### ISSUE TITLE
vocab, [unused] token에 대하여

### ISSUE THREAD

**Issue by JeongWoonPark** [monologg/KoELECTRA#12]
WPM로 vocab을 만드는 과정에서 아래와 같이 unused 토큰을 추가하셨다고 했는데, **어떤 목적으로** 추가하신건가요?

```vocab을 다 만든 후, [unused]token 200개를 vocab에 추가적으로 붙였습니다.```

**Comment by monologg** [comment]
@JeongWoonPark 

**vocab에 없는 새로운 token을 커버**하기 위한 용도입니다.

예를 들어 `코로나`가 vocab에 없는데 이를 추가하고 싶으면 `[unused0]`를 `코로나`로 바꿔 끼우면 되는 겁니다:)

**Comment by monologg** [comment]
@JeongWoonPark 

해당 이슈는 닫도록 하겠습니다! 혹시나 이슈가 있으면 다시 오픈해주시면 됩니다:)

**Comment by JeongWoonPark** [comment]
@monologg 
답변 감사합니다!

사전학습을 다시 하기엔 비용이 많이 들기 때문에, 파인튜닝에서만 `[UNK]`토큰을 방지하기 위한 목적인가요?
