### ISSUE TITLE
단일 GPU 사전학습 이슈 

### ISSUE THREAD

**Issue by JeongWoonPark** [monologg/KoELECTRA#13]
안녕하세요. 단일 GPU(GTX 1080 / 11GB)로 ELECTRA BASE 모델을 학습시켜보고 있습니다.

사전학습 원본 소스(google/electra)의 base, large 부분 주석은 푼 상태이며,
```
    # defaults for different-sized model
    if self.model_size == "small":
      self.embedding_size = 128
    # Here are the hyperparameters we used for larger models; see Table 6 in the
    # paper for the full hyperparameters
    else:
      self.max_seq_length = 512
      self.learning_rate = 2e-4
      if self.model_size == "base":
        self.embedding_size = 768
        self.generator_hidden_size = 0.33333
        self.train_batch_size = 4
      else:
        self.embedding_size = 1024
        self.mask_prob = 0.25
        self.train_batch_size = 2048
```
그 외 파라미터는 다음과 같습니다. (vocab_size는 32,000으로 새로 만들었습니다.)
```
{
  "model_size": "base",
  "train_batch_size": "4",
  "vocab_size": "32000",
  "do_lower_case": "False",
}
```

문제는 사전학습에선 loss가 어느정도 내려가는데, 
![image](https://user-images.githubusercontent.com/45035457/97142274-b0e77900-17a3-11eb-979f-488faa556942.png)

파인튜닝(NSMC)에선 loss가 전혀 내려가지 않고 있습니다. (Acc: 50)
![image](https://user-images.githubusercontent.com/45035457/97142898-f5274900-17a4-11eb-915f-0b46e82e5527.png)

장원님께서 올려주신 `koelectra-base-v3` 사전학습 모델로 같은 파인튜닝 코드를 돌렸을땐 loss가 줄어들어 Acc가 91.34까지 나오는걸 확인했습니다.

현재 이슈는 **TPU / GPU 차이**와 이로 인한 **train-batch size**밖에 없는데...
 혹시 이 외 다른 곳에서 신경쓰신 부분이 있을까요?

**Comment by monologg** [comment]
데이터의 양 등을 알 수 없어서 확실하게 말씀드리긴 어렵지만 개인적으로 **batch size가 원인**이라고 생각합니다. (4는 상당히 작은 사이즈로 생각됩니다)

개인적인 경험으로도 large 모델을 학습할 때 batch size를 작게하면 pretraining loss는 줄어드나 Finetuning loss는 줄어들지 않았습니다.

제안드리는 방법은 base 모델말고 **small 모델로 batch size를 키워서 학습해보는 것을 권장합니다.**

해당 세팅에서도 이슈가 있다면 추가적인 원인 분석이 필요할 것 같습니다.

**Comment by JeongWoonPark** [comment]
@monologg, 안녕하세요. 답변 감사드립니다.
- 학습데이터의 양은 11GB로 국립국어원-모두의 말뭉치에서 신문, 구어 말뭉치를 전처리해 사용했습니다.
- Small 모델 batch size를 20대로 했을 때 정상 작동 확인했습니다.

Small 모델 학습시에도 GPU 메모리 문제로 batch_size를 더 크게 늘릴순 없었습니다...
단일 GPU로는 Small 모델을 제외하고 사용하기 어렵겠네요..

**Comment by monologg** [comment]
@JeongWoonPark 

TFRC 프로그램 신청해서 TPU 사용하는 것도 추천드립니다:)

해당 이슈는 닫도록 하겠습니다
