### ISSUE TITLE
추가학습 관련 질문드립니다.

### ISSUE THREAD

**Issue by myungchulkang** [monologg/KoELECTRA#14]
안녕하세요,

KoELECTRA 모델 너무 잘쓰고 있습니다 :)

성능 향상을 위해 특정 도메인의 한국어 말뭉치를 추가 학습하려고 합니다. 

처음부터 학습하는 것이 아니라 사전 학습된 KoELECTRA 의 가중치를 어떻게 가져올 수 있을까요?

**Comment by monologg** [comment]
안녕하세요

Pretraining 코드는 기본적으로 tensorflow 원본코드로 학습했기에 tensorflow checkpoint를 사용해야 합니다. (https://github.com/google-research/electra#pre-training)

1. README에 있는 tensorflow ckpt 다운로드

2. 파일 이름을 step에 맞게 변경

- data, index, meta 각각 step으로 바꿔서 변경
- checkpoint 파일도 아래 그림과 같은 느낌으로 변경
![image](https://user-images.githubusercontent.com/28896432/99140837-9872cc00-2688-11eb-8428-354c869e188f.png)

3. 추가적으로 학습할 데이터에 대해 tfrecord 만들기

4. config 변경 (기존에 700000 step을 이미 학습한 것이면 config에서는 800000 step으로 변경


-----

저도 직접 해본 것이 아니라 위의 방법에서 버그가 있을 수 있지만, 기본적인 방향성은 맞는 것으로 알고 있습니다:)

감사합니다.

**Comment by myungchulkang** [comment]
말씀해주신 대로 차근차근 해보도록 하겠습니다 👍 

말씀해주신 [페이지](https://github.com/google-research/electra#pre-training)에서 살펴보니, 다음과 같이 걸린다고 나오는데 electra 체크포인트를 그대로 가져와서 continual training 시킬 때 가지고 있는 컴퓨팅 파워로 가능할지 또는 얼마나 걸릴지 가늠해볼 수 있는 방법이 있는건가요?

코랩 pro 환경해서도 가능한걸까요? (GPU: T4 또는 P100 / RAM: 25GB으로 준수하지만, 런 타임 제한이 24시간 등으로 있긴 합니다ㅠ)

`The fully-trained model (~4 days on a v100 GPU) should perform roughly ~` v100 하나로 small 모델 학습은 4일 정도 걸린다고 합니다.

도움 주셔서 정말 감사합니다!

**Comment by monologg** [comment]
@myungchulkang 

개인적으로는 Pretraining은 continual일지라도 **TFRC**를 쓰는 것을 추천합니다 (기본적으로 GCP 계정 생성시 300달러를 무료로 제공해줍니다.)

https://monologg.kr/2020/04/20/tpu-electra/ 에 기본적인 방법은 정리해놓았습니다. 참고하시면 될 것 같습니다.

**Comment by myungchulkang** [comment]
빠르게 답장 주셔서 정말 감사합니다. 조언해주신 방법대로 시도해보겠습니다!!
