### ISSUE TITLE
Finetuning 에 대해서 질문드립니다.

### ISSUE THREAD

**Issue by siasky21** [monologg/KoELECTRA#16]
nsmc 데이터로 finetuning을 하게 되면 small-v3 모델을 불러오는 과정에서 에러가 발생합니다.

small-v2나 base 모델의 경우는 잘 작동이 됩니다.

 "Unable to load weights from pytorch checkpoint file. "
OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

위와 같은 에러가 발생하네요

**Comment by monologg** [comment]
@siasky21 

안녕하세요:)

해당 오류에 대한 재현이 잘 안되는데 (transformers 3.3.1과 3.5.1 둘 다 체크), 혹시 사용한 환경설정에 대해 말씀해주실수 있으실가요?

ex)
OS: Ubuntu 18.04
transformers: 3.3.1
torch: 1.7.0

-------

참고로 최근에 huggingface model 저장소가 리뉴얼 되었는데, 해당 부분으로 인하여 이슈가 발생한걸로 추측하고 있습니다.

https://discuss.huggingface.co/t/announcement-model-versioning-upcoming-changes-to-the-model-hub/1914

**Comment by siasky21** [comment]
OS: Windows 10
transformers: 3.0.2
torch: 1.2.0

torch와 transformers 버전때문인것 같습니다.
이유가 있어서 위의 버전을 사용중인데 아무래도 호환이 안되는 거 같네요.
그럼에도 v2는 작동하는데 v3가 작동을 안하는건 다른 문제가 있나 생각이 듭니다.

**Comment by monologg** [comment]
@siasky21 

아무래도 torch version이 이슈인 것 같습니다. v3를 tf에서 pt로 바꿀때 사용한 torch 버전이 높았던게 이유인것 같습니다

우선은 사용을 위해서 torch version을 1.6 이상으로 바꿔주셔야 할 것 같습니다

해당 부분은 좀 더 확인해보도록 하겠습니다

**Comment by monologg** [comment]
@siasky21 
해당 이슈 관련해서 여러모로 찾아봤는데, v3를 tf에서 pt로 변환할 때 토치 버전에 디펜던시가 있는 것 같습니다ㅠ
`torch >= 1.5` 이여야만 정상작동하는 것 확인했고, 해당 부분 readme에 업데이트 하도록 하겠습니다
