### ISSUE TITLE
Pretrain된 모델의 weight loading 이슈

### ISSUE THREAD

**Issue by archon159** [monologg/KoELECTRA#17]
안녕하세요,

KoElectra를 pytorch와 transformer 모듈에서 사용하려고 하는 도중에 에러가 납니다.

제가 사용한 코드는 

from transformers import ElectraModel, ElectraTokenizer
PRE_TRAINED_MODEL_NAME = 'monologg/koelectra-base-v3-discriminator'
tokenizer = ElectraTokenizer.from_pretrained(PRE_TRAINED_MODEL_NAME)
electra = ElectraModel.from_pretrained(PRE_TRAINED_MODEL_NAME)

위와 같고 에러의 내용은 다음과 같습니다.

OSError: Unable to load weights from pytorch checkpoint file for 'monologg/koelectra-base-v3-discriminator' at '/home/archon159/.cache/torch/transformers/efc891feb2c6ce810e4350a7fb9d7f9f48d16b78cc24f95c34bd2d5d1d4bb9c4.03eea45db3698b9b1139a0ea93942bdc069b09fd0bb6fd8002f56146135a2cc0'If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

혹시 이 현상의 해결법을 알려주시면 감사하겠습니다.
그리고 KoElectra를 implement할 때 사용하셨던 transformers와 pytorch 버전도 알려주시면 좋을 것 같습니다.
감사합니다.

**Comment by archon159** [comment]
추가로 다른 버전의 KoElectra를 사용해 봤는데,base-v2-discriminator는 문제없이 작동합니다.
v3 버전의 문제인 것 같습니다.

**Comment by monologg** [comment]
@archon159 

안녕하세요:)

해당 오류에 대한 재현이 잘 안되는데 (transformers 3.3.1과 3.5.1 둘 다 체크), 혹시 사용한 환경설정에 대해 말씀해주실수 있으실가요?

ex)
OS: Ubuntu 18.04
transformers: 3.3.1
torch: 1.7.0

-------

참고로 최근에 huggingface model 저장소가 리뉴얼 되었는데, 해당 부분으로 인하여 이슈가 발생한걸로 추측하고 있습니다.

https://discuss.huggingface.co/t/announcement-model-versioning-upcoming-changes-to-the-model-hub/1914

**Comment by archon159** [comment]
현재 제가 사용하고 있는 환경은 다음과 같습니다.

OS: Centos 7.7.1908
transformers: 3.5.1
torch: 1.4.0

감사합니다.

**Comment by monologg** [comment]
@archon159 

저 역시도 해당 이슈가 재현이 되네요

아무래도 torch version이 이슈인 것 같습니다. v3를 tf에서 pt로 바꿀때 사용한 torch 버전이 높았던게 이유인것 같습니다

해당 부분은 좀 더 확인해보도록 하겠습니다

**Comment by archon159** [comment]
torch version을 1.7을 사용하니 해결이 되네요.
감사합니다.
