### ISSUE TITLE
허깅페이스 파이프라인

### ISSUE THREAD

**Issue by Huffon** [monologg/KoELECTRA#2]
안녕하세요 ! 
먼저 좋은 자료 공유 너무 감사합니다.
리소스가 부족한 스타트업에서 아주 요긴하게 사용될 것 같습니다 😆

다름이 아니라 다운스트림 태스크로 감정 분석, 개체명 인식을 수행해주셨는데,
혹시 해당 모델들을 허깅페이스 파이프라인으로 구축하실 의향이 있으신가요?

KoELECTRA를 활용해 개체명 인식 결과를 활용하는 관련한 토이 프로젝트를 해보려고 하는데 
파이프라인으로도 구축하실 계획이 있으신지 궁금합니다 !

**Comment by monologg** [comment]
안녕하세요:)

파이프라인 제작까지는 계획에 없긴했는데, Documentation 참고해서 우선 nsmc부터 한번 차근차근 만들어보겠습니다. 금방 공유해드릴 수 있을 꺼 같네요:)

**Comment by monologg** [comment]
WIP #3

**Comment by monologg** [comment]
@Huffon 

이전부터 NER Pipeline 쪽에서 **한 단어가 여러 개의 piece로 쪼개지는 경우**가 고려되지 않는 이슈가 있었는데 아직도 해결이 안된 것 같네요...
- https://github.com/huggingface/transformers/issues/3548
- https://github.com/huggingface/transformers/issues/2488

----

가장 안전하게 결과를 뽑아내는 방법은 아래일 거 같긴 합니다. 물론 이 코드도 tokenize를 다시 한다는 비효율이 존재하고, 현재로서는 불가피한 것 같습니다. 해당 부분에 대해서는 염두에 두시면 좋을 것 같습니다.

```python
from transformers import pipeline, AutoModelForTokenClassification, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("dbmdz/electra-large-discriminator-finetuned-conll03-english")
model = AutoModelForTokenClassification.from_pretrained("dbmdz/electra-large-discriminator-finetuned-conll03-english")
ner = pipeline("ner",
               model=model,
               tokenizer=tokenizer,
               ignore_labels=[]  # To show every token result
               )

# Assuming that `.` is also tagged as `O` in dataset
text = "Statue of Liberty is located in New York ."
output = ner(text)
output = output[1:-1]  # Ignore [CLS] & [SEP]

words = text.split()
tokens_mask = []
for word in words:
    word_tokens = tokenizer.tokenize(word)
    if not word_tokens:
        word_tokens = [tokenizer.unk_token]  # For handling the bad-encoded word
    tokens_mask.extend([1] + [0] * (len(word_tokens) - 1))

assert len(tokens_mask) == len(output)

word_idx = 0
for mask, token in zip(tokens_mask, output):
    if mask == 1:
        token["word"] = words[word_idx]
        word_idx += 1
        print(token)
```

**Comment by monologg** [comment]
`NERPipeline` 클래스를 직접 customize 방안도 있겠군요:)

**Comment by Huffon** [comment]
나이브하게 Prefix를 달고 있는 토큰들은 이전에 등장한 토큰들에 붙여주는건 예외가 많이 발생할까요?
저는 위 레퍼런스들을 보며 허깅페이스 예제 코드 결과들에 **B 태그**가 등장하지 않는 점으로 인해 엔티티를 한 번에 묶어주는게 어려울 것 같다고 생각했습니다 !

예로 위에 제시해주신 결과 값에서 New York이 
```
{'word': 'New', 'score': 0.9989102482795715, 'entity': 'I-LOC'}
{'word': 'York', 'score': 0.9989310503005981, 'entity': 'I-LOC'}
```
로 쪼개어서 나타나는데, 아래와 같이 B 태그가 있으면 New York 스팬을 한 번에 추출하는게 쉬울텐데요...

```
{'word': 'New', 'score': 0.9989102482795715, 'entity': 'B-LOC'}
{'word': 'York', 'score': 0.9989310503005981, 'entity': 'I-LOC'}
```

혹시 Naver NER 에 Fine-tuned 된 KoELECTRA 모델들은 B 태그를 잘 추출해주나요?

**Comment by monologg** [comment]
> 나이브하게 Prefix를 달고 있는 토큰들은 이전에 등장한 토큰들에 붙여주는건 예외가 많이 발생할까요?
> 저는 위 레퍼런스들을 보며 허깅페이스 예제 코드 결과들에 **B 태그**가 등장하지 않는 점으로 인해 엔티티를 한 번에 묶어주는게 어려울 것 같다고 생각했습니다 !
> 
> 예로 위에 제시해주신 결과 값에서 New York이
> 
> ```
> {'word': 'New', 'score': 0.9989102482795715, 'entity': 'I-LOC'}
> {'word': 'York', 'score': 0.9989310503005981, 'entity': 'I-LOC'}
> ```
> 
> 로 쪼개어서 나타나는데, 아래와 같이 B 태그가 있으면 New York 스팬을 한 번에 추출하는게 쉬울텐데요...
> 
> ```
> {'word': 'New', 'score': 0.9989102482795715, 'entity': 'B-LOC'}
> {'word': 'York', 'score': 0.9989310503005981, 'entity': 'I-LOC'}
> ```
> 
> 혹시 Naver NER 에 Fine-tuned 된 KoELECTRA 모델들은 B 태그를 잘 추출해주나요?

몇 가지 문장으로 테스트해보고 있는데 B태그 부분은 잘 추출하는 것 같습니다.

다만 F1-Score이 높은 점수는 아닌지라 오차는 감안을 해야할 것 같습니다.

테스트만 마무리하면 곧 Pipeline 공개해 드릴 수 있을 것 같습니다:)

```text
[{'entity': 'PER-B', 'score': 0.9999827742576599, 'word': '문재인'},
 {'entity': 'CVL-B', 'score': 0.999975323677063, 'word': '대통령은'},
 {'entity': 'DAT-B', 'score': 0.9999777674674988, 'word': '28일'},
 {'entity': 'LOC-B', 'score': 0.9998270273208618, 'word': '서울'},
 {'entity': 'AFW-B', 'score': 0.9999445676803589, 'word': '코엑스에서'},
 {'entity': 'O', 'score': 0.9999942183494568, 'word': '열린'},
 {'entity': 'EVT-B', 'score': 0.999899685382843, 'word': '‘데뷰'},
 {'entity': 'EVT-I', 'score': 0.9832422137260437, 'word': '(Deview)'},
 {'entity': 'EVT-I', 'score': 0.9992077946662903, 'word': '2019’'},
 {'entity': 'O', 'score': 0.9999943375587463, 'word': '행사에'},
 {'entity': 'O', 'score': 0.9999971985816956, 'word': '참석해'},
 {'entity': 'O', 'score': 0.9999986886978149, 'word': '젊은'},
 {'entity': 'CVL-B', 'score': 0.999980092048645, 'word': '개발자들을'},
 {'entity': 'O', 'score': 0.9999975562095642, 'word': '격려하면서'},
 {'entity': 'O', 'score': 0.9902618527412415, 'word': '우리'},
 {'entity': 'O', 'score': 0.9999471306800842, 'word': '정부의'},
 {'entity': 'TRM-B', 'score': 0.999969482421875, 'word': '인공지능'},
 {'entity': 'O', 'score': 0.999995768070221, 'word': '기본구상을'},
 {'entity': 'O', 'score': 0.9999942779541016, 'word': '내놓았다.'},
 {'entity': 'O', 'score': 0.9999710321426392, 'word': '출처'},
 {'entity': 'O', 'score': 0.9999939203262329, 'word': ':'},
 {'entity': 'ORG-B', 'score': 0.9999638199806213, 'word': '미디어오늘'},
 {'entity': 'TRM-B', 'score': 0.8900746703147888, 'word': '(http://www.mediatoday.co.kr)'}]
```

**Comment by monologg** [comment]
> 안녕하세요!
> 
> 파이프라인 제작까지는 계획에 없긴했는데, Documentation 참고해서 우선 nsmc부터 한번 차근차근 만들어보겠습니다. 금방 공유해드릴 수 있을 꺼 같네요:)

[KoELECTRA-Pipeline](https://github.com/monologg/KoELECTRA-Pipeline)

제작 완료하여 공유합니다:)
