### ISSUE TITLE
vocab 생성 문의

### ISSUE THREAD

**Issue by Jimojimojimo** [monologg/KoELECTRA#26]
안녕하세요~ 좋은정보 잘 보고 있습니다!

vocab 관련해서 궁금한 점이 있습니다.
KoELECTRA-v3 모델에서 Mecab과 Wordpiece를 이용하여 새로 제작하셨다고 했는데 단순히 wordpiece만 사용하지 않고 mecab을 쓰신 이유가 있나요?
mecab을 사용하지 않고 vocab을 생성한 후 학습하여 do_eval한 결과 disc_precision = 0.0, disc_recall = 0.0로 학습이 잘 되지 않았습니다.
그 후에 mecab으로 자른 후 vocab을 생성한 후 학습하였더니 학습이 잘 되었습니다. 2가지 경우 모두 똑같은 코드를 사용하여 학습을 했는데 이런 결과가 나오게 되었는데 한국어 특성상 그런걸까요?
도움 주시면 감사하겠습니다.

**Comment by soonilbae** [comment]
NLP 초보자입니다. KLUE Paper 4.1을 확인하였는데, 궁금한 것이 있습니다.
Mecab으로 pretokenize한다는 것이 전체 코퍼스를 단순히 형태소 단위로만
분리하여 wordpiece로 학습한다는 의미인가요?
논문의 예제를 보니 단순히 형태소 단위로 분리하는 것 이상의 전처리가 필요한 
것이 아닌가하는 생각이 들어서요. 초보자이다 보니 너무 간단한 질문을 하게
되는 것 같습니다. 갑사합니다.
