### ISSUE TITLE
사전학습 모델 파일 문의

### ISSUE THREAD

**Issue by goreng2** [monologg/KoELECTRA#37]
## Checklist

- [x] I've searched the project's [`issues`]

## ❓ Question

안녕하세요. 좋은 모델 공유에 감사드립니다.

KoELECTRA에 **추가 사전학습**을 수행해보려 합니다.

`ELECTRA = Discriminator + Generator` 라고 명명했을 때, 공유해주신 모델들은 `ELECTRA`가 아닌, `Discriminator`와 `Generator` 뿐일까요?

`Tensorflow-v1`의 경우에도 `Discriminator`의 `TF1` 버전일 뿐인지 문의드립니다.

## 📎 Additional context

![image](https://user-images.githubusercontent.com/45035457/182570381-aa655f17-d3c5-4ec9-af8d-4e074812bea9.png)

**Comment by monologg** [comment]
> ELECTRA = Discriminator + Generator 라고 명명했을 때, 공유해주신 모델들은 ELECTRA가 아닌, Discriminator와 Generator 뿐일까요?

ELECTRA 모델은 Discriminator와 Generator 두 개를 이용하여 학습하는 구조이기 때문에 discriminator와 generator만 존재합니다.
자세한 아키텍쳐와 사용법은 electra 원 논문을 참고하시면 좋을 것 같습니다.

> Tensorflow-v1의 경우에도 Discriminator의 TF1 버전일 뿐인지 문의드립니다.

tensorflow v1 체크포인트에는 discriminator, generator가 같이 포함되어 있습니다.
https://github.com/google-research/electra 참고하시면 될 것 같습니다.

**Comment by goreng2** [comment]
답변 감사드립니다.
