### ISSUE TITLE
position embedding 크기 수정

### ISSUE THREAD

**Issue by iambogeumkim** [monologg/KoELECTRA#40]
안녕하세요 만들어주신 모델과 제가 가진 데이터셋을 이용해 파인튜닝을 진행하고 있는 학생입니다 🙂

혼자 이것저것 검색해보면서 코드를 다루다가 (word_embeddings): Embedding(a, 128, padding_idx=0)의 a 값과  (position_embeddings): Embedding(512, 128)부분에서 : The size of tensor a (35000) must match the size of tensor b (512) at non-singleton dimension 1 에러를 만나게 되었습니다.

word_embeddings 사이즈를 줄이면 out of bounds가 떠서 일단 vocab_size로 맞춰 놓은 상태입니다. 저기에 맞춰 position embedding 차원을 늘이고 싶은데 가능한지+가능하다면 어떤 식으로 해야 할지 여쭤봅니다.

한국어 데이터로 좋은 모델 만들어주셔서 감사합니다!

**Comment by monologg** [comment]
언급하신 이슈가 발생한 정확한 원인, 과정을 알수 없어 정확한 답변을 드리긴 어려울꺼 같습니다.

vocab size에 맞춰서 변경하고 싶다면 `model.resize_token_embeddings` 를 사용하시면 될 것 같습니다.

https://huggingface.co/docs/transformers/main/en/main_classes/model#transformers.PreTrainedModel.resize_token_embeddings

https://github.com/huggingface/transformers/blob/9393f966bcebd112b25f84e46af6e349525406c7/examples/pytorch/language-modeling/run_mlm.py#L392

**Comment by iambogeumkim** [comment]
좀 더 찾아보고 다른 방법도 고안해보겠습니다. 빠른 답변 감사합니다!
