### ISSUE TITLE
vocab.txt

### ISSUE THREAD

**Issue by Moon-sung-woo** [monologg/KoELECTRA#5]
안녕하세요! 우선 KoELECTRA 소스코드를 공유해 주셔서 감사합니다.

저는 딥러닝 관련해서 공부하고 있는 학생입니다.

공유해주신 소스코드를 차근차근 보고 있는데 preprocessing하신 코드가 없는건지 아님 제가 못찾는건지 모르겠어서 이슈 남기게 됐습니다.

**Comment by monologg** [comment]
안녕하세요:)

Preprocessing한 코드는 제가 따로 공개하지 않았습니다.

로직의 경우는 [preprocessing.md](https://github.com/monologg/KoELECTRA/blob/master/docs/preprocessing.md)에서 명시한 것과 동일합니다. 다만 데이터별로 일부는 다르게 적용한 것은 있습니다.

감사합니다.

**Comment by Moon-sung-woo** [comment]
빠른 답변 너무 감사합니다! 
finetune을 원래 설정대로 8에폭을 돌려
koelectra-base-nsmc-ckpt를 얻었는데 이걸가지고 inference를 돌리려면
eval해준거처럼 돌리면 될까요??

**Comment by monologg** [comment]
> 빠른 답변 너무 감사합니다!
> finetune을 원래 설정대로 8에폭을 돌려
> koelectra-base-nsmc-ckpt를 얻었는데 이걸가지고 inference를 돌리려면
> eval해준거처럼 돌리면 될까요??

예 그렇습니다. 해당 부분의 코드를 참고하여서 제작하시면 될꺼 같습니다.

Huggingface Transformers의 `Pipeline`을 사용하는 것도 하나의 방법이 될 것 같습니다

[KoELECTRA-Pipeline](https://github.com/monologg/KoELECTRA-Pipeline) 참고해보셔도 될 것 같습니다:)

**Comment by Moon-sung-woo** [comment]
감사합니다! 참고하여 만들어보도록 하겠습니다!
