### ISSUE TITLE
Is there any published paper describing your work?

### ISSUE THREAD

**Issue by ilya-palachev** [monologg/KoELECTRA#7]
Hello,

First of all, thank you for publishing this repository. Is there any published paper describing your work? I mean a paper in some journal or conference proceedings. This information would help to understand your work a lot.

Thanks in advance!

**Comment by monologg** [comment]
@ilya-palachev 

Hi:)

There is no paper for my `KoELECTRA` work.

Basically, most of the code is same as original `ELECTRA` paper.

4 docs below is the information that I can give.

- https://github.com/monologg/KoELECTRA/blob/master/README_EN.md
- https://github.com/monologg/KoELECTRA/blob/master/docs/preprocessing_EN.md
- https://github.com/monologg/KoELECTRA/blob/master/docs/tpu_training_EN.md
- https://github.com/monologg/KoELECTRA/blob/master/docs/wordpiece_vocab_EN.md

**Comment by ilya-palachev** [comment]
OK, thanks! @monologg Are there any plans to make a paper?

**Comment by monologg** [comment]
> OK, thanks! @monologg Are there any plans to make a paper?

Sadly, I have no plan for paper. Thank you:)

**Comment by ilya-palachev** [comment]
OK, have a nice day!
