### ISSUE TITLE
maximum sequence length

### ISSUE THREAD

**Issue by EJHyun** [monologg/KoELECTRA#8]
훌륭한 모델 감사합니다!

저는 이 모델을 이용해서 sentence embedding을 만들어보려고 embedding을 추출하고 있는 학생입니다.

그런데 

Token indices sequence length is longer than the specified maximum sequence length for this model (511 > 512). Running this sequence through the model will result in indexing errors

InvalidArgumentError: indices[0,512] = 512 is not in [0, 512) [Op:ResourceGather]

이런 오류가 뜹니다.
제 코드는

![image](https://user-images.githubusercontent.com/56884260/90721267-6228e900-e2f3-11ea-8e3f-d9e50296eab5.png)

이구요

도와주시면 너무 감사할 것 같습니다.

**Comment by monologg** [comment]
전체 코드가 있는 것이 아니어서 확실하진 않지만 `encode_plus`에서 512를 초과하는 것이 truncate되지 않은 이유일 것으로 보는데

```python
encoded_input = tokenizer.encode_plus(
    text=s,
    max_length=512,
    padding="max_length",
    truncation=True,
    add_special_tokens=True,
    return_tensors="tf",
)
```

이렇게 시도해주실 수 있으실까요? (transformers==3.0.2 기준 코드입니다)

**Comment by EJHyun** [comment]
빠른 답변 감사드립니다!
덕분에 해결되었어요 ㅎㅎ
